#!/bin/bash
# Update ssh-agent authentication socket for tmux

if [[ $_ = $0 ]] ; then
	echo "This script must be sourced to work properly."
	exit 1
fi

if [[ -n $TMUX ]] ; then
	NEW_SSH_AUTH_SOCK=`tmux showenv | grep "^SSH_AUTH_SOCK" | cut -d = -f 2`
	if [[ -n $NEW_SSH_AUTH_SOCK ]] && [[ -S $NEW_SSH_AUTH_SOCK ]] ; then
		SSH_AUTH_SOCK=$NEW_SSH_AUTH_SOCK
	fi
fi
