#!/usr/bin/env python
from __future__ import print_function
import argparse
from urllib2 import urlopen

from lxml import etree

def main():
    parser = make_argparser()
    args = parser.parse_args()

    try:
        get_herds(args)
    except KeyboardInterrupt:
        return

def get_herds(args):
    xml = 'http://www.gentoo.org/proj/en/metastructure/herds/herds.xml'
    tree = etree.HTML(urlopen(xml).read())
    herds = [dev.getparent().getprevious().getprevious().text for dev in
             tree.xpath('//li') if dev.text.startswith(args.developer)]
    print('\n'.join(herds))

def make_argparser():
    parser = argparse.ArgumentParser()
    parser.add_argument('developer',
        help='email address of the developer to search for herds')
    return parser

if __name__ == '__main__':
    main()
